# -*- coding: utf-8 -*-
"""TB PIK FINAL DIRMA .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HPo0J6gIrB5GBDD3n4DrNvTw4Fdq_fl3
"""

# QUIZ SEDERHANA
import json
import os
import random
from datetime import datetime

SOAL_FILE = "soal.json"
SKOR_FILE = "skor.json"
JAWABAN_FILE = "jawaban.json"

# DEFAULT DATA
DEFAULT_SOAL = DEFAULT_SOAL = [
    {
        "pertanyaan": "1. Urutan planet dalam tata surya yang benar dari Matahari adalah?",
        "pilihan": ["Venus-Merkurius-Bumi", "Merkurius-Venus-Bumi", "Bumi-Merkurius-Venus", "Venus-Bumi-Merkurius", "Merkurius-Bumi-Venus"],
        "jawaban_index": 1
    },
    {
        "pertanyaan": "2. Bilangan prima terbesar di bawah 50 adalah?",
        "pilihan": ["43", "47", "49", "41", "37"],
        "jawaban_index": 1
    },
    {
        "pertanyaan": "3. Reaksi fotosintesis terjadi di bagian sel tumbuhan bernama?",
        "pilihan": ["Mitokondria", "Kloroplas", "Ribosom", "Inti sel", "Sitoplasma"],
        "jawaban_index": 1
    },
    {
        "pertanyaan": "4. Kerajaan Hindu-Buddha yang terkenal dengan Candi Borobudur adalah?",
        "pilihan": ["Sriwijaya", "Majapahit", "Medang", "Tarumanegara", "Kutai"],
        "jawaban_index": 2
    },
    {
        "pertanyaan": "5. Hasil dari 12 × 12 + 24 ÷ 2 adalah?",
        "pilihan": ["168", "144", "156", "150", "160"],
        "jawaban_index": 2
    },
    {
        "pertanyaan": "6. Unsur kimia dengan simbol ‘Fe’ adalah?",
        "pilihan": ["Ferro", "Ferrum", "Ferit", "Ferum", "Fiber"],
        "jawaban_index": 1
    },
    {
        "pertanyaan": "7. Negara yang pertama kali menemukan teknologi mesin uap adalah?",
        "pilihan": ["Jerman", "Prancis", "Amerika Serikat", "Inggris", "Belanda"],
        "jawaban_index": 3
    },
    {
        "pertanyaan": "8. Penyebab utama terjadinya gerhana bulan adalah?",
        "pilihan": [
            "Bulan berada di antara Matahari dan Bumi",
            "Bumi berada di antara Matahari dan Bulan",
            "Matahari berada di antara Bumi dan Bulan",
            "Orbit Bulan berubah",
            "Jarak Bulan ke Bumi mengecil"
        ],
        "jawaban_index": 1
    },
    {
        "pertanyaan": "9. Konversi 2,5 jam ke detik adalah?",
        "pilihan": ["7200 detik", "7500 detik", "8000 detik", "9000 detik", "8500 detik"],
        "jawaban_index": 3  # 2.5 jam = 2.5 × 3600 = 9000
    },
    {
        "pertanyaan": "10. Fungsi utama enzim amilase adalah mengubah?",
        "pilihan": ["Lemak menjadi gliserol", "Protein menjadi asam amino", "Gula sederhana menjadi energi", "Pati menjadi gula", "Air menjadi ion"],
        "jawaban_index": 3
    },
    {
        "pertanyaan": "11. Perang Dunia II berakhir pada tahun?",
        "pilihan": ["1942", "1943", "1944", "1945", "1946"],
        "jawaban_index": 3
    },
    {
        "pertanyaan": "12. Teori Big Bang menjelaskan tentang?",
        "pilihan": [
            "Penciptaan bumi",
            "Asal usul tata surya",
            "Ledakan besar awal mula alam semesta",
            "Pembentukan bintang",
            "Awal mula kehidupan manusia"
        ],
        "jawaban_index": 2
    },
    {
        "pertanyaan": "13. Hasil dari √225 adalah?",
        "pilihan": ["10", "11", "12", "13", "14"],
        "jawaban_index": 2
    },
    {
        "pertanyaan": "14. Alat untuk mengukur intensitas cahaya adalah?",
        "pilihan": ["Lux meter", "Barometer", "Higrometer", "Kaliper", "Spektrometer"],
        "jawaban_index": 0
    },
    {
        "pertanyaan": "15. Satuan internasional untuk gaya adalah?",
        "pilihan": ["Joule", "Pascal", "Watt", "Newton", "Ampere"],
        "jawaban_index": 3
    },
    {
        "pertanyaan": "16. Di Indonesia, peristiwa G30S terjadi pada tahun?",
        "pilihan": ["1955", "1960", "1965", "1970", "1975"],
        "jawaban_index": 2
    },
    {
        "pertanyaan": "17. Rumus luas segitiga adalah?",
        "pilihan": [
            "alas × tinggi",
            "(alas × tinggi) ÷ 2",
            "alas + tinggi",
            "(alas + tinggi) × 2",
            "alas² + tinggi²"],
        "jawaban_index": 1
    },
    {
        "pertanyaan": "18. Tumbuhan berwarna hijau karena mengandung?",
        "pilihan": ["Hemoglobin", "Melanin", "Klorofil", "Karoten", "Lutein"],
        "jawaban_index": 2
    },
    {
        "pertanyaan": "19. Negara yang dijuluki 'Negeri Tirai Bambu' adalah?",
        "pilihan": ["Jepang", "Korea Selatan", "Vietnam", "Tiongkok", "Thailand"],
        "jawaban_index": 3
    },
    {
        "pertanyaan": "20. Bagian komputer yang berfungsi sebagai 'otak' pemrosesan adalah?",
        "pilihan": ["RAM", "VGA", "SSD", "CPU", "ROM"],
        "jawaban_index": 3
    }
]

DEFAULT_SKOR = []
DEFAULT_JAWABAN = []

# Utility load/save JSON
def load_json(path, default):
    if not os.path.exists(path):
        with open(path, "w", encoding="utf-8") as f:
            json.dump(default, f, indent=2, ensure_ascii=False)
        return default
    try:
        with open(path, "r", encoding="utf-8") as f:
            return json.load(f)
    except:
        return default

def save_json(path, data):
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)

soal_data = load_json(SOAL_FILE, DEFAULT_SOAL)
skor_data = load_json(SKOR_FILE, DEFAULT_SKOR)
jawaban_data = load_json(JAWABAN_FILE, DEFAULT_JAWABAN)

# STREAMLIT
def coba_jalankan_streamlit():
    try:
        import streamlit as st
        import matplotlib.pyplot as plt

        st.title("📘 Aplikasi Quiz Sederhana")

        menu = st.sidebar.selectbox(
            "Menu",
            ["Mulai Quiz", "Tambah Soal", "Riwayat Nilai & Jawaban", "Grafik Nilai", "Keluar"]
        )
#  NENU MULAI QUIZ
        if menu == "Mulai Quiz":
            st.header("📝 Mulai Quiz")
            nama = st.text_input("Masukkan Nama Anda:")
            if not nama:
                st.warning("Silakan masukkan nama sebelum mulai.")
                st.stop()

            if "quiz_state" not in st.session_state:
                random.shuffle(soal_data)
                st.session_state.quiz_state = {
                    "index": 0,
                    "benar": 0,
                    "soal": soal_data.copy(),
                    "nama": nama,
                    "jawaban_user": [],
                    "sudah_jawab": False
                }

            qs = st.session_state.quiz_state
            total = len(qs["soal"])
            idx = qs["index"]

            if idx < total:
                data = qs["soal"][idx]
                st.write(f"Soal **{idx+1}/{total}**")
                st.subheader(data["pertanyaan"])

                pilihan = data["pilihan"]
                jawab = st.radio("Jawaban:", pilihan, disabled=qs["sudah_jawab"])

                if st.button("Kirim", disabled=qs["sudah_jawab"]):
                    j = pilihan.index(jawab)
                    benar = (j == data["jawaban_index"])
                    qs["jawaban_user"].append({
                        "soal": data["pertanyaan"],
                        "jawaban": jawab,
                        "benar": benar
                    })
                    if benar:
                        st.success("Benar! 🎉")
                        qs["benar"] += 1
                    else:
                        st.error(f"Salah. Jawaban benar: **{pilihan[data['jawaban_index']]}**")
                    qs["sudah_jawab"] = True

                if qs["sudah_jawab"]:
                    if st.button("NEXT ➜"):
                        qs["index"] += 1
                        qs["sudah_jawab"] = False
                        st.rerun()

            else:
                skor = round(100 * qs["benar"] / total, 2)
                st.subheader("🎉 Quiz Selesai!")
                st.write(f"Benar: {qs['benar']} / {total}")
                st.write(f"Nilai: {skor}")

                skor_data.append({
                    "timestamp": datetime.now().isoformat(timespec="seconds"),
                    "nama": qs["nama"],
                    "skor": skor,
                    "benar": qs["benar"],
                    "total": total
                })
                save_json(SKOR_FILE, skor_data)

                jawaban_data.append({
                    "timestamp": datetime.now().isoformat(timespec="seconds"),
                    "nama": qs["nama"],
                    "hasil": qs["jawaban_user"]
                })
                save_json(JAWABAN_FILE, jawaban_data)

                if st.button("Mulai Lagi"):
                    del st.session_state.quiz_state
                    st.rerun()

#MENU RIWAYAT NILAI & JAWABAN
        if menu == "Riwayat Nilai & Jawaban":
            st.header("📄 Riwayat Nilai & Jawaban Peserta")

            if not skor_data and not jawaban_data:
                st.info("Belum ada data.")
            else:
                st.subheader("📌 Riwayat Nilai Peserta")
                if skor_data:
                    for i, e in enumerate(skor_data, start=1):
                        st.write(
                            f"**{i}.** {e['timestamp']} — **{e['nama']}** "
                            f"— Nilai: **{e['skor']}** ({e['benar']}/{e['total']})"
                        )
                else:
                    st.info("Belum ada nilai peserta.")

                st.write("---")

                st.subheader("📌 Riwayat Jawaban Peserta")
                if jawaban_data:
                    for data_user in jawaban_data:
                        st.markdown(f"### 👤 {data_user['nama']}  \n⏱️ *{data_user['timestamp']}*")
                        for j in data_user["hasil"]:
                            st.write(f"- **{j['soal']}**")
                            st.write(f"  Jawaban: {j['jawaban']}")
                            st.write(f"  Status: {'Benar ✅' if j['benar'] else 'Salah ❌'}")
                        st.write("---")
                else:
                    st.info("Belum ada riwayat jawaban.")

# MENU GRAFIK NILAI
        if menu == "Grafik Nilai":
            st.header("📊 Grafik Nilai")
            if not skor_data:
                st.info("Belum ada nilai.")
            else:
                tipe_grafik = st.selectbox("Pilih tipe grafik:", ["Garis", "Batang", "Diagram Lingkaran"])

                nama_peserta = [e["nama"] for e in skor_data]
                nilai = [e["skor"] for e in skor_data]
                benar = [e["benar"] for e in skor_data]
                total = [e["total"] for e in skor_data]

                if tipe_grafik == "Garis":
                    fig, ax = plt.subplots(figsize=(8, 4))
                    ax.plot(nama_peserta, nilai, marker="o", linestyle='-', color='blue')
                    ax.set_title("Perkembangan Nilai Peserta")
                    ax.set_ylabel("Nilai")
                    ax.set_xlabel("Peserta")
                    plt.xticks(rotation=45)
                    st.pyplot(fig)

                elif tipe_grafik == "Batang":
                    fig, ax = plt.subplots(figsize=(8, 4))
                    ax.bar(nama_peserta, nilai, color='green')
                    ax.set_title("Nilai Peserta")
                    ax.set_ylabel("Nilai")
                    ax.set_xlabel("Peserta")
                    plt.xticks(rotation=45)
                    st.pyplot(fig)

                elif tipe_grafik == "Diagram Lingkaran":
                    total_benar = sum(benar)
                    total_salah = sum([t - b for t, b in zip(total, benar)])
                    fig, ax = plt.subplots(figsize=(6, 6))
                    ax.pie(
                        [total_benar, total_salah],
                        labels=["Benar", "Salah"],
                        autopct="%1.1f%%",
                        colors=["skyblue", "salmon"]
                    )
                    ax.set_title("Persentase Benar vs Salah Semua Peserta")
                    st.pyplot(fig)

# MENU KELUAR
        if menu == "Keluar":
            st.title("👋 Terima Kasih Telah Menggunakan Aplikasi!")
            st.success("Anda telah keluar dari aplikasi.")
            st.session_state.clear()
            st.stop()

        return True

    except:
        return False


def mode_terminal():
    print("Streamlit tidak terdeteksi → Mode Terminal aktif.")


if not coba_jalankan_streamlit():
    mode_terminal()